<?php
/**
 * @copyright 2012 Future Publishing Ltd
 * @license   http://opensource.org/licenses/mit-license.php/ MIT
 */

namespace Future\Metricsd;

/**
 * Test class for Client.
 * Generated by PHPUnit on 2012-08-09 at 15:11:44.
 *
 * @author    Joseph Ray <joseph.ray@futurenet.com>
 */
class ClientTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Data provider for testTiming and testHistogram
     *
     * @return array
     */
    public function timingProvider()
    {
        return array(
            array(
                'hello',
                1234
            ),
            array(
                'foobar',
                12.459403
            )
        );
    }

    /**
     * @covers Future\Metricsd\Client::send
     * @covers Future\Metricsd\Client::__construct
     * @covers Future\Metricsd\Client::timing
     * @covers Future\Metricsd\Client::histogram
     * @dataProvider timingProvider
     *
     * @param string $stat The stat name
     * @param float  $time The time to log
     *
     * @return void
     */
    public function testTiming($stat, $time)
    {
        $connection = $this->getMock('\Future\Network\Connection', array('send'));
        $client     = new Client($connection, true, 'www.test.com.');
        $connection->expects($this->once())
            ->method('send')
            ->with($this->equalTo("www.test.com.$stat:$time|h"));

        $client->timing($stat, $time);
    }

    /**
     * @covers Future\Metricsd\Client::send
     * @covers Future\Metricsd\Client::__construct
     * @covers Future\Metricsd\Client::histogram
     * @dataProvider timingProvider
     *
     * @param string $stat The stat name
     * @param float  $time The time to log
     *
     * @return void
     */
    public function testHistogram($stat, $time)
    {
        $connection = $this->getMock('\Future\Network\Connection', array('send'));
        $client     = new Client($connection, true, 'www.test.com.');
        $connection->expects($this->once())
            ->method('send')
            ->with($this->equalTo("www.test.com.$stat:$time|h"));

        $client->histogram($stat, $time);
    }

    /**
     * Data provider for testGuage
     *
     * @return array
     */
    public function guageProvider()
    {
        return array(
            array(
                'hello',
                1234
            ),
            array(
                'foobar',
                12.459403
            )
        );
    }

    /**
     * @covers Future\Metricsd\Client::send
     * @covers Future\Metricsd\Client::__construct
     * @covers Future\Metricsd\Client::guage
     * @dataProvider guageProvider
     *
     * @param string $stat  The stat name
     * @param float  $value The time to log
     *
     * @return void
     */
    public function testGuage($stat, $value)
    {
        $connection = $this->getMock('\Future\Network\Connection', array('send'));
        $client     = new Client($connection, true, 'www.test.com.');
        $connection->expects($this->once())
            ->method('send')
            ->with($this->equalTo("www.test.com.$stat:$value|g"));

        $client->guage($stat, $value);
    }

    /**
     * Data provider for testMeter
     *
     * @return array
     */
    public function meterProvider()
    {
        return array(
            array('meter')
        );
    }

    /**
     * @covers Future\Metricsd\Client::send
     * @covers Future\Metricsd\Client::__construct
     * @covers Future\Metricsd\Client::meter
     * @dataProvider meterProvider
     *
     * @param string $meter The stat name
     *
     * @return void
     */
    public function testMeter($meter)
    {
        $connection = $this->getMock('\Future\Network\Connection', array('send'));
        $client     = new Client($connection, true, 'www.test.com.');
        $connection->expects($this->once())
            ->method('send')
            ->with($this->equalTo("www.test.com.$meter"));

        $client->meter($meter);
    }

    /**
     * Data provider for testIncrement
     *
     * @return array
     */
    public function incrementProvider()
    {
        return array(
            array('increment')
        );
    }

    /**
     * @covers Future\Metricsd\Client::send
     * @covers Future\Metricsd\Client::__construct
     * @covers Future\Metricsd\Client::increment
     * @dataProvider incrementProvider
     *
     * @param string $stat Stat name
     *
     * @return void
     */
    public function testIncrement($stat)
    {
        $connection = $this->getMock('\Future\Network\Connection', array('send'));
        $client     = new Client($connection, true, 'www.test.com.');
        $connection->expects($this->once())
            ->method('send')
            ->with($this->equalTo("www.test.com.$stat:1|c"));

        $client->increment($stat);
    }

    /**
     * Data provider for testDecrement
     *
     * @return array
     */
    public function decrementProvider()
    {
        return array(
            array('decrement')
        );
    }

    /**
     * @covers Future\Metricsd\Client::send
     * @covers Future\Metricsd\Client::__construct
     * @covers Future\Metricsd\Client::decrement
     * @dataProvider decrementProvider
     *
     * @param string $stat Stat name
     *
     * @return void
     */
    public function testDecrement($stat)
    {
        $connection = $this->getMock('\Future\Network\Connection', array('send'));
        $client     = new Client($connection, true, 'www.test.com.');
        $connection->expects($this->once())
            ->method('send')
            ->with($this->equalTo("www.test.com.$stat:-1|c"));

        $client->decrement($stat);
    }

    /**
     * Data provider for testUpdateStats
     *
     * @return array
     */
    public function updateStatsProvider()
    {
        return array(
            array(
                'foobar',
                1234
            ),
            array(
                'negative',
                -1234
            )
        );
    }

    /**
     * @covers Future\Metricsd\Client::send
     * @covers Future\Metricsd\Client::__construct
     * @covers Future\Metricsd\Client::updateStats
     * @dataProvider updateStatsProvider
     *
     * @param string $stat  Stat name
     * @param int    $delta The delta to update the value with
     *
     * @return void
     */
    public function testUpdateStats($stat, $delta)
    {
        $connection = $this->getMock('\Future\Network\Connection', array('send'));
        $client     = new Client($connection, true, 'www.test.com.');
        $connection->expects($this->once())
            ->method('send')
            ->with($this->equalTo("www.test.com.$stat:$delta|c"));

        $client->updateStats($stat, $delta);
    }

    /**
     * Data provider for testDelete
     *
     * @return array
     */
    public function deleteProvider()
    {
        return array(
            array(
                'test',
                Client::TYPE_COUNT
            ),
            array(
                'hasd;lkj3',
                Client::TYPE_GUAGE
            )
        );
    }

    /**
     * @covers Future\Metricsd\Client::send
     * @covers Future\Metricsd\Client::__construct
     * @covers Future\Metricsd\Client::delete
     * @dataProvider deleteProvider
     *
     * @param string $stat Stat name
     * @param string $type Stat type
     *
     * @return void
     */
    public function testDelete($stat, $type)
    {
        $connection = $this->getMock('\Future\Network\Connection', array('send'));
        $client     = new Client($connection, true, 'www.test.com.');
        $connection->expects($this->once())
            ->method('send')
            ->with($this->equalTo("www.test.com.$stat:delete|$type"));

        $client->delete($stat, $type);
    }

    /**
     * @covers Future\Metricsd\Client::send
     * @covers Future\Metricsd\Client::__construct
     * @covers Future\Metricsd\Client::meter
     */
    public function testDisabled()
    {
        $connection = $this->getMock('\Future\Network\Connection', array('send'));
        $client     = new Client($connection, false, 'www.test.com.');
        $connection->expects($this->never())
            ->method('send');

        $client->meter('neverCall');
    }
}